// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-37NlQ1jUaitJu8E6xBh5uYzBgCvM2A',
    appId: '1:763809770179:web:e4760f7e8279a6e6951076',
    messagingSenderId: '763809770179',
    projectId: 'stproject-264be',
    authDomain: 'stproject-264be.firebaseapp.com',
    storageBucket: 'stproject-264be.appspot.com',
    measurementId: 'G-JWJ8CKWRFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASKeY1Ma8Sjtu9stFYXORHwWB3az8eHfI',
    appId: '1:763809770179:android:f3ee9c92ab6fccdb951076',
    messagingSenderId: '763809770179',
    projectId: 'stproject-264be',
    storageBucket: 'stproject-264be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSsQ1OfhWCcxTt38hlUcV2HdrKv7l8t0',
    appId: '1:763809770179:ios:7def06c6cb4314fe951076',
    messagingSenderId: '763809770179',
    projectId: 'stproject-264be',
    storageBucket: 'stproject-264be.appspot.com',
    iosBundleId: 'com.example.flutter1stProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkSsQ1OfhWCcxTt38hlUcV2HdrKv7l8t0',
    appId: '1:763809770179:ios:596f117978f1390c951076',
    messagingSenderId: '763809770179',
    projectId: 'stproject-264be',
    storageBucket: 'stproject-264be.appspot.com',
    iosBundleId: 'com.example.flutter1stProject.RunnerTests',
  );
}
